name: nepali_date_picker
description: Material and Cupertino Styled Date Picker, Date Range Picker and Calendar with Bikram Sambat(Nepali) Support.
version: 5.3.2
homepage: https://github.com/sarbagyastha/nepali_date_picker

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nepali_utils: ^3.0.3
  flutter_layout_grid: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: Nepali Date Picker Demo
    path: demo.gif
  - description: Nepali Date Picker Example
    path: screenshot/picker.png
  - description: Nepali Date Calendar Example
    path: screenshot/calendar.png
